# Build the Go Binary.
FROM golang:1.17 as build_strava-api
ENV CGO_ENABLED 0
ARG BUILD_REF 

# Copy the source code into the container.
COPY . /service

# Build the service binary.
WORKDIR /service/app/services/strava-api
RUN go build -ldflags "-X main.build=${BUILD_REF}"

# Run the Go Binary in Alpine.
FROM alpine:3.15
ARG BUILD_DATE
ARG BUILD_REF
COPY --from=build_strava-api /service/app/services/strava-api/strava-api /service/strava-api
WORKDIR /service
CMD ["./strava-api"]