apiVersion: apps/v1
kind: Deployment
metadata:
  name: strava-pod
  namespace: strava-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: strava
  template:
    metadata:
      labels:
        app: strava
    spec:
      containers:
      # strava-api container configuration
      - name: strava-api
        resources:
          limits:
            cpu: "2000m" # Up to 2 full cores
          requests:
            cpu: "1000m" # Use 1 full cores