apiVersion: apps/v1
kind: Deployment
metadata:
  name: strava-upload
  namespace: strava
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strava-upload
  template:
    metadata:
      labels:
        app: strava-upload
    spec:
      containers:
      - name: strava-upload
        image: adiazny/easy-strava-upload:0.6.0
        ports:
        - containerPort: 8090
        env:
        - name: STRAVA_CLIENT_ID
          value: [value]
        - name: STRAVA_CLIENT_SECRET
          value: [value]
        - name: STRAVA_REFRESH_TOKEN
          value: [value]
---
apiVersion: v1
kind: Service
metadata:
  name: strava-svc
  namespace: strava
spec:
  selector:
    app: strava-upload
  type: LoadBalancer
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strava-ui
  namespace: strava
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strava-ui
  template:
    metadata:
      labels:
        app: strava-ui
    spec:
      containers:
      - name: strava-ui
        image: adiazny/easy-strava-ui:0.6.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: strava-ui-svc
  namespace: strava
spec:
  selector:
    app: strava-ui
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080