---
apiVersion: v1
kind: ConfigMap
metadata:
  name: strava-upload-config
  namespace: strava
data:
  REDIS_ADDRESS: redis-svc:6379
  REDIS_PASSWORD: ""
  REDIS_DB: "0"
  STRAVA_CLIENT_ID: ""
  STRAVA_CLIENT_SECRET: ""
  STRAVA_REFRESH_TOKEN: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strava-upload
  namespace: strava
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strava-upload
  template:
    metadata:
      labels:
        app: strava-upload
    spec:
      containers:
      - name: strava-upload
        image: adiazny/easy-strava-upload:0.7.0
        ports:
        - containerPort: 8090
        envFrom:
          - configMapRef:
              name: strava-upload-config
---
apiVersion: v1
kind: Service
metadata:
  name: strava-svc
  namespace: strava
spec:
  selector:
    app: strava-upload
  type: LoadBalancer
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strava-ui
  namespace: strava
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strava-ui
  template:
    metadata:
      labels:
        app: strava-ui
    spec:
      containers:
      - name: strava-ui
        image: adiazny/easy-strava-ui:0.7.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: strava-ui-svc
  namespace: strava
spec:
  selector:
    app: strava-ui
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
